### ISSUE TITLE
A way to disable enchanted books dropping on kills

### ISSUE THREAD

**Issue by VortexSlurge** [TinyModularThings/UniqueEnchantments#103] opened 2024-07-06 17:11 UTC
Hi, I have an infection-like mod in my server and so many enchanted books keep spawning lagging my world slowly but surely. One could say the enchanted book drop rate is the real infection mod. I only just downloaded the 5.0.0 version yesterday and thats when the problem began.

**Comment by Xaikii** [comment] 2024-07-07 14:15
Duplicate of #101

**Closed as completed by Xaikii** 2024-07-07 14:15 UTC
