### ISSUE TITLE
UniqueEnchantments-Battle.toml replicates itself on every launch of the game

### ISSUE THREAD

**Issue by Not-February** [TinyModularThings/UniqueEnchantments#36] opened 2021-08-11 21:16 UTC
This is even without any changes to the config file.

It will start with ``UniqueEnchantment-Battle-1.toml.bak`` and then continue to add numbers to each additional file with each launch of the game. It doesn't seem to be resetting the values in the config when it does this, but it does make the config folder more cluttered than it needs to be.

``Unique+Enchantments+Battle-1.16.5-1.0``
``Unique+Enchantments-1.16.5-2.0.1``
``Forge 36.2.0``

**Comment by Speiger** [comment] 2021-08-12 04:17
@Febilian could you provide a gamelog where that happened. Because this means a config entry is expecting something different then what is provided. (Yes i hate this forge feature)

Otherwise this might be addressed in the next version since we are redoing basically the entire mod if you have seen how many changes i did in the 1.12 branch. (1.14 is going to be tested soonish by @Xaikii )

**Comment by Not-February** [comment] 2021-08-12 06:24
Here's a ``latest.log`` with nothing but the aforementioned installed.

https://gist.github.com/Febilian/d84d1c72c775c19e34a6ceec020b67ff

**Comment by Speiger** [comment] 2021-08-12 07:08
Yeah this should be addressed in the next patch.

**Comment by Speiger** [comment] 2021-08-13 15:31
@Febilian sorry to say this seems to be a forge bug to some degree at least.
Because we "just" ported the mod from 1.14-1.16 and whenever we change a config entry it does that.
And from investigations is that the config "reader" just reads null values and provides a false positive.

There is not much we actually can do.

Edit: the startup "should" be fixed where we can but changing configs will 100% cause this to repeat.

**Comment by Not-February** [comment] 2021-08-15 00:18
For what it's worth, I've seen this same thing happen with some other mods too. It may or may not be the same thing?

https://github.com/Ellpeck/NaturesStarlight/issues/1
https://github.com/team-abnormals/allurement/issues/9

**Comment by Speiger** [comment] 2021-08-15 08:28
@Febilian from what i can tell is its a forge problem unless its with Arrays (represented as []) if these reset on startup or just dont allow any input then someone used normal define for a listdefine (code).

To describe the problem: Basically forge reads the config and parses it over the config definition that each mod has made. (Template) the issue is that the "The config has changed" has a flaw that it just reads 0 things. Like after reading a config it read 0 things. Not everytime, but a lot more times then you think. And that triggers: Oh i have a incorrect config file i have to fix it.
But when fixing the config it has nothing to "fix" resulting in this message: error correcting. (Nothing got corrected)

A "HackFix" is to validate that forge actually read the config. But good luck getting the "Forge Gods" to admit they made a mistake xD

**Closed as completed** 2021-08-16 16:30 UTC
