### ISSUE TITLE
Crash with Compact Fun Ores

### ISSUE THREAD

**Issue by WenXin20** [TinyModularThings/UniqueEnchantments#10] opened 2020-02-03 23:22 UTC
`Minecraft v1.14.4`
`Forge v28.1.117`
`Unique Enchantments v1.8`
[`Compact Ores v1.2.0`](https://www.curseforge.com/minecraft/mc-mods/compact-ores) 
[`Fun Ores v2.4.1+15`](https://www.curseforge.com/minecraft/mc-mods/fun-ores)

In the `compactores.toml` file, I had added Fun Ores to the config, but found out that my game will crash after breaking a Compact Zombie Ore. I assume it crashes because it tries to retrieve items from a mob loot table and it looks like Unique Enchantments has to be installed for the crash to occur.

Config: [compactores.zip](https://github.com/DoubleNegation/CompactOres/files/4146487/compactores.zip) 

[Crash Report](https://gist.github.com/WenXin20/f221126ba7795818666f39a42eee12c5)

More detailed info at: DoubleNegation/CompactOres#6

**Comment by Speiger** [comment] 2020-02-21 21:39
@WenXin20 as stated by the CompactOres Dev thats not a UE bug.
Closing.
Sorry for the long ignoring we missed it and had a lot of IRL stuff to do.

**Closed as completed by Speiger** 2020-02-21 21:39 UTC

**Comment by WenXin20** [comment] 2020-02-21 21:47
It's alright. But it does say that it's a UE bug in his second comment?

**Comment by Speiger** [comment] 2020-02-21 21:54
well the issue is that the event that is thrown by the Destruction is missing data we need. If it is not present then this is the issue.

**Comment by WenXin20** [comment] 2020-02-21 22:03
Ah, ok
